version: '3'

services:

        app:
           build: .
           container_name: app
           entrypoint: dockerize -template .docker/app/.env.example:.env -wait tcp://db:3306 -timeout 40s .docker/entrypoint.sh
           environment: 
             - DB_HOST=db
             - DB_DATABASE=laravel
             - DB_USERNAME=root
             - DB_PASSWORD=root   
           volumes:
             - .:/var/www
           networks: 
             - app-network
           depends_on:
             - db
             - redis

        nginx:
           build: .docker/nginx
           container_name: nginx
           entrypoint: dockerize -template /etc/nginx/conf.d/nginx.conf.template:/etc/nginx/conf.d/nginx.conf
           environment: 
             - NGINX_PORT=80
           tty: true
           ports:
             - "8080:80"
           volumes:
             - .:/var/www
           networks:
             - app-network
           depends_on:
             - app
             
        db:
           build: .docker/mysql
           command: --innodb-use-native-aio=0
           container_name: db
           restart: always
           tty: true
           ports:
               - "3306:3306"
           volumes:
            - ./.docker/dbdata:/var/lib/mysql           
           environment:
               - MYSQL_DATABASE=laravel
               - MYSQL_ROOT_PASSWORD=root
               - MYSQL_USER=root
           networks:
              - app-network

        redis:
          image: redis:alpine
          container_name: redis
          expose:
             - 6379
          networks:
             - app-network

networks:
  app-network:
          driver: bridge
